# Generated by Django 3.2.6 on 2021-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='isCompleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
