# Generated by Django 3.2.6 on 2021-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='isCompleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
