# Generated by Django 3.2.6 on 2021-08-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todomodel_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='isCompleted',
            new_name='is_completed',
        ),
    ]
